import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import { Providers } from "./providers";
import { fetchCategoriesWithSubcategoriesServer } from "@/services/products.server";
import type { CategoryWithSubcategories } from "@/types/productTypes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
  variable: '--font-lexend',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const categoriesWithSubcategories: CategoryWithSubcategories[] = await fetchCategoriesWithSubcategoriesServer()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={lexend.variable}>
      <body>
        <Providers>
            <Navbar categoriesWithSubcategories={categoriesWithSubcategories}/>
            <main className="bg-[var(--background-color)] text-gray-900 min-h-screen flex flex-col">
            {children}
            </main>
            <Footer />
        </Providers>
      </body>
    </html>
  );
}
